site_name: 'Inoa Satellite Gateway'
theme:
  name: 'material'
nav:
  - Home: 'index.md'
  - 'User Guide':
    - 'Electrical Installation': user-guide/electrical-installation.md
  - 'Technical Documentation':
    - 'Electric Metering Module': technical-guide/metering-module.md
    - 'SoC Module': technical-guide/soc-module.md
    - 'Ethernet Module': technical-guide/ethernet-module.md
    - 'Panel Module': technical-guide/panel-module.md
    - 'Mieterstrom Module': technical-guide/mieterstrom-module.md
    - 'M-Bus Module': technical-guide/mbus-module.md
    - 'CT Module': technical-guide/ct-module.md
    - 'Debug Module': technical-guide/debug-module.md
    - 'Development Board': technical-guide/development-board.md
  - 'Developer Guide':
    - 'Getting Started': developer-guide/getting-started.md