name: Dev

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # ~~~~~~~~~~~~~~~
      # SoC Module
      # ~~~~~~~~~~~~~~~
      - name: KiCad::SoC-Module::Docs
        uses: nerdyscout/kicad-exports@v2.2
        with:
          config: configs/ci.kibot.yaml
          dir: out
          schema: 'soc-module/soc-module.sch'
          board: 'soc-module/soc-module.kicad_pcb'
      # ~~~~~~~~~~~~~~~
      # Ethernet Module
      # ~~~~~~~~~~~~~~~
      - name: KiCad::Ethernet-Module::Model
        uses: nerdyscout/kicad-exports@v2.2
        with:
          config: configs/ci.kibot.yaml
          dir: out
          schema: 'ethernet-extension/ethernet-extension.sch'
          board: 'ethernet-extension/ethernet-extension.kicad_pcb'
      # ~~~~~~~~~~~~~~~
      # Panel Module
      # ~~~~~~~~~~~~~~~
      - name: KiCad::Panel-Module::Model
        uses: nerdyscout/kicad-exports@v2.2
        with:
          config: configs/ci.kibot.yaml
          dir: out
          schema: 'panel-module/panel-module.sch'
          board: 'panel-module/panel-module.kicad_pcb'
      # ~~~~~~~~~~~~~~~
      # Upload
      # ~~~~~~~~~~~~~~~
      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: out
