name: Dev

on:
  push:
    paths:
    - '**.kicad_sch'
    - '**.kicad_pcb'
    - '**.yml'
    - '**.yaml'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.yml'
      - '**.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Panel Module
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: electrics/kibot.yaml
        dir: out/
        schema: electrics/panel-module/panel-module.kicad_sch
        board: electrics/panel-module/panel-module.kicad_pcb
    - name: Ethernet Module
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: electrics/kibot.yaml
        dir: out/
        schema: electrics/ethernet-extension/ethernet-extension.kicad_sch
        board: electrics/ethernet-extension/ethernet-extension.kicad_pcb
    - name: Metering Module
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: electrics/kibot.yaml
        dir: out/
        schema: electrics/metering-module/metering-module.kicad_sch
        board: electrics/metering-module/metering-module.kicad_pcb
    - name: SoC Module
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: electrics/kibot.yaml
        dir: out/
        schema: electrics/soc-module/soc-module.kicad_sch
        board: electrics/soc-module/soc-module.kicad_pcb
    - name: Mieterstrom Module
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: electrics/kibot.yaml
        dir: out/
        schema: electrics/mieterstrom-module/mieterstrom-module.kicad_sch
        board: electrics/mieterstrom-module/mieterstrom-module.kicad_pcb
