name: Main

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Panel Module
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: electrics/kibot.yaml
        dir: out/
        schema: electrics/panel-module/panel-module.kicad_sch
        board: electrics/panel-module/panel-module.kicad_pcb
    - name: Ethernet Module
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: electrics/kibot.yaml
        dir: out/
        schema: electrics/ethernet-extension/ethernet-extension.kicad_sch
        board: electrics/ethernet-extension/ethernet-extension.kicad_pcb
    - name: Metering Module
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: electrics/kibot.yaml
        dir: out/
        schema: electrics/metering-module/metering-module.kicad_sch
        board: electrics/metering-module/metering-module.kicad_pcb
    - name: SoC Module
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: electrics/kibot.yaml
        dir: out/
        schema: electrics/soc-module/soc-module.kicad_sch
        board: electrics/soc-module/soc-module.kicad_pcb
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Cache
      uses: actions/cache@v2
      with:
        key: ${{ github.ref }}
        path: .cache
    - run: pip install mkdocs-material 
    - run: cp -r out/3d docs/generated
    - run: cp -r out/bom docs/generated
    - run: cp -r out/schematics docs/generated
    - run: mkdocs build


